jobs:
- job: BuildWindowsWithSonarQube
  displayName: Build for Windows\MSBuild With SonarQube
  pool:
    vmImage: 'windows-latest'
  variables:
    BUILD_WRAPPER_DOWNLOAD_URL: <SONARQUBE_HOST_URL>/static/cpp/build-wrapper-win-x86.zip # Replace <SONARQUBE_HOST_URL> with your SonarQube server URL
  steps:
  # Make Build Wrapper available
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'azure-sq' # Name of the SonarQube service endpoint you created
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: "sonar.cfamily.build-wrapper-output=build_wrapper_output_directory"
  - pwsh: |
      curl --create-dirs -sSLo $HOME\.sonar\build-wrapper-win-x86.zip ${{variables.BUILD_WRAPPER_DOWNLOAD_URL}}
      unzip -o $HOME\.sonar\build-wrapper-win-x86.zip -d $HOME\.sonar\
    displayName: Download and install build wrapper
  - pwsh: |
      $path = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1
      & "$HOME\.sonar\build-wrapper-win-x86\build-wrapper-win-x86-64.exe" --out-dir build_wrapper_output_directory $path sonar_scanner_example.vcxproj /t:rebuild
    workingDirectory: .
    displayName: Build in build-wrapper
  - task: SonarQubeAnalyze@4
